INSERT INTO `posts` VALUES (1, 'Đây là thiết kế nhà ở trên Sao Hỏa được NASA thưởng 500.000 USD: 4 tầng đầy đủ tiện nghi, chống bức xạ, in 3D bằng robot', 'Tri thức trẻ', 'Trong tương lai, các phi hành gia sẽ sống trong những khối kiến trúc có tên Marsha, với đầy đủ tiện nghi và đảm bảo an toàn.');
INSERT INTO `posts` VALUES (2, 'Samsung đã lên kế hoạch về chip 3nm, liệu chúng ta có thấy chip 1nm trong tương lai?', 'Tri thức trẻ', 'Về mặt kỹ thuật điều này là hoàn toàn có thể, nhưng các trở ngại về kinh tế có thể khiến những con chip này chỉ xuất hiện trong phòng thí nghiệm mà thôi.');
INSERT INTO `posts` VALUES (3, 'Nếu đã chán Windows hay Mac, bạn có thể thử ngay phiên bản hệ điều hành Linux cực kỳ thân thiện với người dùng này', 'Tri thức trẻ', 'Mặc dù Zorin OS 15 được xây dựng dựa trên nền tảng Linux, nhưng nó đã được tùy biến để phù hợp với những người mới bắt đầu, tập trung vào sự đơn giản và dễ sử dụng.');
INSERT INTO `posts` VALUES (4, 'Super Mario vừa được chế thành game \"battle royale\": 75 người cùng chơi xem ai phá đảo đầu tiên', 'tess', 'Chơi thử nhanh lên trước khi phiên bản Super Mario 75 người chơi bị đóng cửa!');
INSERT INTO `posts` VALUES (5, 'Smartphone chuyên game ASUS ROG Phone 2 sẽ ra mắt vào ngày 23/7, màn hình 120Hz, Snadragon 855, giá từ 14,8 triệu', 'taa', 'tadsdsda');
INSERT INTO `posts` VALUES (6, 'Xiaomi bị tố ăn cắp 3 tác phẩm của nhà thiết kế, kết hợp lại để làm ảnh quảng cáo cho mình', 'đâs', 'dsadasdasfasdas');
INSERT INTO `posts` VALUES (7, 'Netflix công bố phiên bản Samurai của Game Of Thrones với tựa đề \"Age of Samurai: Battle For Japan\"', 'qưeqwdasd', 'sadasdwedfsafsad');
INSERT INTO `posts` VALUES (8, 'Lại có thêm một chiếc smartphone với cụm camera sau siêu to khổng lồ sắp được ra mắt', 'đágáug', 'gjhsgdhjgsadjhasnasvdnsvandbvsanbdvasd');
INSERT INTO `posts` VALUES (9, 'Trên tay Xiaomi Mi Band 4: Không thể đòi hỏi gì hơn với mức giá chỉ vài trăm nghìn', 'ấdasdsa', 'yaudgasdgajhdvja');
INSERT INTO `posts` VALUES (10, 'Ming-Chi Kuo: Cả 3 mẫu iPhone 2020 đều sẽ có màn hình OLED, nhưng chỉ có 2 mẫu hỗ trợ 5G', 'iphone', 'ádgasjhdasdasndadszxz');
INSERT INTO `posts` VALUES (11, 'Chip Qualcomm Snapdragon 865 lộ những thông số đầu tiên, sẽ có hai biến thể khác nhau', 'android', 'agugsjhbsbdjagsdsa');
INSERT INTO `posts` VALUES (12, 'Đánh giá Xiaomi Mi 9: Mức giá làm nên tất cả', 'mi', 'áduasgdjbhadasd');
INSERT INTO `posts` VALUES (13, 'Bản chất của thành phần sapphire trên ống kính smartphone là gì?', 'saphia', 'áhsajhdkjasjasdsdasds');
INSERT INTO `posts` VALUES (14, 'Xiaomi ra mắt máy dạy tiếng Anh tích hợp từ điển, giá 1,7 triệu đồng', 'xiaomim', 'jasbjdbasdasdzx');
INSERT INTO `posts` VALUES (15, 'Nhiều người không nhận ra rằng, Apple không phải thứ đồ mua để sĩ diện, mà lại cực kỳ thực tế', 'apple', 'hjabjbdasdbzsczx');
INSERT INTO `posts` VALUES (16, 'Quên tăng độ sáng màn hình, Apple tưởng MacBook Pro của người dùng bị hỏng và bỏ ra hơn 10.000 USD để bảo hành', 'ưqeqwe', 'adszxczxc');
INSERT INTO `posts` VALUES (17, 'ádasdczxc', 'ádasdasd', 'adasdasd');
INSERT INTO `posts` VALUES (18, 'Tiêu đề 1', 'Tác giả 1', 'Nôi dung 1');
INSERT INTO `posts` VALUES (19, 'Tiêu đê 2', 'Tác giả 2', 'Nội dung 2');
INSERT INTO `posts` VALUES (20, 'Tiêu đề 3', 'Tác giả 1', 'Nội dung 3');
INSERT INTO `posts` VALUES (21, 'Tiêu đề 1', 'Tác giả 3', 'Nội dung 4');
INSERT INTO `posts` VALUES (22, 'Tiêu đề 4', NULL, NULL);
INSERT INTO `posts` VALUES (23, 'Tiêu đề 5', NULL, NULL);
INSERT INTO `posts` VALUES (24, 'Tiêu đề 6', NULL, NULL);
INSERT INTO `posts` VALUES (25, 'Tiêu đề 7', NULL, NULL);
INSERT INTO `posts` VALUES (26, 'Tiêu đề 8', NULL, NULL);
INSERT INTO `posts` VALUES (27, 'Tiêu đề 9', NULL, NULL);
INSERT INTO `posts` VALUES (28, 'Tiêu đề 10', NULL, NULL);
INSERT INTO `posts` VALUES (29, 'Tiêu đề 11', NULL, NULL);
INSERT INTO `posts` VALUES (30, 'Tiêu đề 12', NULL, NULL);
INSERT INTO `posts` VALUES (31, 'Tiêu đề 13', NULL, NULL);
INSERT INTO `posts` VALUES (32, 'Tiêu đề 14', NULL, NULL);
INSERT INTO `posts` VALUES (33, 'Tiêu đề 15', NULL, NULL);
